BEGIN;

INSERT INTO categories (name, slug, sort_order)
VALUES
    ('AirPods', 'airpods', 10),
    ('iPhone', 'iphone', 20),
    ('MacBook', 'macbook', 30),
    ('iPad', 'ipad', 40)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    sort_order = EXCLUDED.sort_order;

UPDATE products SET is_active = FALSE;
UPDATE product_variants SET is_active = FALSE;
DELETE FROM product_images;

INSERT INTO products (
    category_id,
    name,
    slug,
    description,
    advantages,
    main_image,
    is_popular,
    is_new,
    is_hit,
    sort_order
)
VALUES
    (
        (SELECT id FROM categories WHERE slug = 'airpods'),
        'AirPods 4',
        'airpods-4',
        'Легкие беспроводные наушники для повседневного использования.',
        '["Легкие наушники на каждый день: быстро подключаются к iPhone, удобно сидят и не перегружают ухо даже после долгих звонков или прогулок.", "Персонализированное пространственное аудио добавляет объема музыке, фильмам и играм, поэтому звук ощущается шире, чем у обычных вкладышей.", "В версии с активным шумоподавлением можно приглушить улицу, транспорт и офисный фон, а режим прозрачности помогает не выпадать из происходящего вокруг.", "Кейс USB-C компактный и легко помещается в карман, поэтому AirPods 4 удобно брать с собой без отдельной сумки или лишних проводов."]'::jsonb,
        'Assets/desktop/photo/airpods4/airpods-4.png',
        FALSE,
        TRUE,
        FALSE,
        10
    ),
    (
        (SELECT id FROM categories WHERE slug = 'airpods'),
        'AirPods Pro 3',
        'airpods-pro-3',
        'Флагманские внутриканальные наушники с шумоподавлением.',
        '["Сильное активное шумоподавление помогает сосредоточиться в метро, самолете, коворкинге или дома, когда вокруг слишком много лишних звуков.", "Внутриканальная посадка дает плотный контакт и более насыщенный бас, а несколько размеров амбушюр помогают подобрать комфортную посадку под себя.", "Персонализированное пространственное аудио с отслеживанием движений головы делает фильмы, клипы и игры более живыми и объемными.", "Датчики для тренировок и улучшенная автономность делают AirPods Pro 3 не только наушниками для музыки, но и удобным повседневным аксессуаром."]'::jsonb,
        'Assets/desktop/photo/airpodsPro3/airpods-pro-3.png',
        TRUE,
        TRUE,
        TRUE,
        20
    ),
    (
        (SELECT id FROM categories WHERE slug = 'airpods'),
        'AirPods Max 2',
        'airpods-max-2',
        'Полноразмерные наушники Apple с премиальным звучанием.',
        '["Полноразмерная посадка мягко закрывает ухо и лучше изолирует от внешнего шума, поэтому AirPods Max 2 комфортны для долгих сессий дома, в дороге и на работе.", "Активное шумоподавление и режим прозрачности позволяют быстро переключаться между полным погружением и разговором с людьми рядом.", "Персонализированное пространственное аудио раскрывает фильмы и музыку объемнее, а через USB-C доступно прослушивание с минимальной задержкой.", "Корпус выглядит заметно и премиально, а выбор цветов помогает подобрать наушники под свой стиль, не превращая их в скучный рабочий гаджет."]'::jsonb,
        'Assets/desktop/photo/airpodsMax2/airpods-max-blue.png',
        TRUE,
        FALSE,
        TRUE,
        30
    ),
    (
        (SELECT id FROM categories WHERE slug = 'iphone'),
        'iPhone 17e',
        'iphone-17e',
        'Доступная модель iPhone с актуальным дизайном и свежими цветами.',
        '["iPhone 17e сохраняет главное ощущение актуального iPhone: быстрый интерфейс, понятную камеру, стабильные обновления iOS и аккуратный дизайн без лишней переплаты.", "Модель хорошо подходит для связи, учебы, фото, банковских приложений и повседневных задач, когда нужен надежный смартфон без профессиональных наворотов.", "Поддержка eSIM и SIM + eSIM помогает удобно разделить личный и рабочий номера или оставить запасной тариф для поездок.", "Спокойные цвета корпуса легко сочетаются с чехлами и аксессуарами, поэтому телефон выглядит чисто и не надоедает через пару недель."]'::jsonb,
        'Assets/desktop/photo/iphone17E/iphone-17e-black.png',
        FALSE,
        TRUE,
        FALSE,
        100
    ),
    (
        (SELECT id FROM categories WHERE slug = 'iphone'),
        'iPhone 17',
        'iphone-17',
        'Базовая модель нового поколения для ежедневного использования.',
        '["6.3-дюймовый Super Retina XDR экран с ProMotion до 120Hz делает прокрутку, игры и анимации заметно плавнее, а картинку — яркой даже на улице.", "48MP Dual Fusion камера хорошо подходит и для обычных фото, и для широких кадров, поэтому можно снимать повседневные моменты без отдельной камеры.", "Ceramic Shield 2 на фронтальной панели дает лучшую защиту от царапин, так что телефон спокойнее переживает карман, сумку и ежедневную суету.", "A19 и несколько вариантов памяти дают хороший баланс скорости, автономности и цены: это универсальный iPhone для тех, кто хочет актуальную модель без Pro-переплаты."]'::jsonb,
        'Assets/desktop/photo/iphone17/iPhone_17_Sage/iphone-17-sage.png',
        TRUE,
        TRUE,
        FALSE,
        110
    ),
    (
        (SELECT id FROM categories WHERE slug = 'iphone'),
        'iPhone Air',
        'iphone-air',
        'Тонкий iPhone с eSIM и легким корпусом.',
        '["iPhone Air выбирают за ощущение в руке: он очень тонкий, легкий и визуально отличается от обычных моделей, но остается полноценным современным iPhone.", "Корпус удобно носить в кармане, маленькой сумке или без чехла, если хочется максимально чистый и минималистичный формат.", "48MP Fusion камера закрывает основные сценарии: фото на каждый день, видео, портреты и быстрые снимки без долгой настройки.", "Это хороший вариант для тех, кому важны дизайн, eSIM, свежий форм-фактор и ощущение нового устройства, а не максимальный набор Pro-функций."]'::jsonb,
        'Assets/desktop/photo/iphoneAir/iphone-air-sky-blue.png',
        TRUE,
        TRUE,
        FALSE,
        120
    ),
    (
        (SELECT id FROM categories WHERE slug = 'iphone'),
        'iPhone 17 Pro',
        'iphone-17-pro',
        'Профессиональная модель с расширенными возможностями.',
        '["A19 Pro и новая система охлаждения помогают дольше держать высокую производительность в играх, монтаже, съемке видео и тяжелых приложениях.", "48MP Pro Fusion камера с телеобъективом дает больше свободы: можно снимать крупные планы, портреты и дальние объекты без резкой потери качества.", "ProMotion-дисплей с высокой яркостью и Ceramic Shield 2 спереди делают телефон приятным для контента и более спокойным в ежедневном использовании.", "iPhone 17 Pro подходит тем, кто часто снимает, работает с медиа, играет и хочет компактный флагман без перехода на самый большой корпус."]'::jsonb,
        'Assets/desktop/photo/iphone17PPM/iPhone_17_PPM_Silver/iphone-17-pro-max-silver.png',
        FALSE,
        TRUE,
        TRUE,
        130
    ),
    (
        (SELECT id FROM categories WHERE slug = 'iphone'),
        'iPhone 17 Pro Max',
        'iphone-17-pro-max',
        'Флагманская модель с большим экраном и максимальной автономностью.',
        '["Большой 6.9-дюймовый экран удобен для видео, игр, карт, таблиц и монтажа коротких роликов, когда хочется больше пространства без планшета.", "A19 Pro, теплопроводный корпус и vapor chamber рассчитаны на долгую нагрузку, поэтому Pro Max увереннее чувствует себя в тяжелых задачах.", "48MP Pro Fusion камера с оптическими вариантами зума помогает снимать и широкий план, и детали издалека, сохраняя флагманское качество картинки.", "Это максимальный iPhone для тех, кому важны автономность, большой дисплей, топовая камера и ощущение устройства с запасом на несколько лет."]'::jsonb,
        'Assets/desktop/photo/iphone17PPM/iPhone_17_PPM_Orange/iphone-17-pro-max-cosmic-orange.png',
        TRUE,
        TRUE,
        TRUE,
        140
    ),
    (
        (SELECT id FROM categories WHERE slug = 'ipad'),
        'iPad 11 A16 2025',
        'ipad-11-a16-2025',
        'Базовый iPad с A16 для учебы, работы и развлечений.',
        '["A16 делает базовый iPad быстрым для учебы, заметок, браузера, видео, презентаций и простого монтажа, не превращая планшет в сложный профессиональный инструмент.", "11-дюймовый Liquid Retina экран удобен для лекций, сериалов, рисования и чтения, а корпус остается достаточно легким для рюкзака.", "Поддержка Apple Pencil и клавиатурных аксессуаров помогает превратить iPad в рабочую тетрадь, мини-ноутбук или экран для творчества.", "Версии Wi-Fi и LTE дают выбор: взять планшет только для дома и учебы или пользоваться интернетом в дороге без раздачи с телефона."]'::jsonb,
        'Assets/desktop/photo/ipad11/ipad-a16-2025-wifi-blue.png',
        TRUE,
        TRUE,
        FALSE,
        200
    ),
    (
        (SELECT id FROM categories WHERE slug = 'ipad'),
        'iPad Pro 11 M5 2025',
        'ipad-pro-11-m5-2025',
        'Компактный iPad Pro на M5 для работы с графикой и контентом.',
        '["M5 дает iPad Pro 11 большой запас мощности для графики, монтажа, 3D, многозадачности и приложений с Apple Intelligence.", "Ultra Retina XDR экран на tandem OLED показывает глубокий черный, высокую яркость и точный контраст, поэтому фото, видео и дизайн выглядят особенно чисто.", "11-дюймовый формат остается компактным: его удобно держать в руках, брать на пары, встречи и использовать как мобильную студию.", "Поддержка Apple Pencil Pro, Magic Keyboard и быстрых беспроводных стандартов делает этот iPad гибким инструментом для учебы, работы и творчества."]'::jsonb,
        'Assets/desktop/photo/ipadProM5/ipad-pro-11-m5-2025-wifi-space-black.png',
        TRUE,
        TRUE,
        TRUE,
        210
    ),
    (
        (SELECT id FROM categories WHERE slug = 'ipad'),
        'iPad Pro 13 M5 2025',
        'ipad-pro-13-m5-2025',
        'Большой iPad Pro на M5 с максимальным пространством для работы.',
        '["13-дюймовый Ultra Retina XDR экран дает больше пространства для таймлайнов, холста, таблиц, нот и документов, поэтому работать можно почти как за ноутбуком.", "M5 уверенно тянет тяжелые творческие задачи: обработку фото, видео, иллюстрации, музыкальные проекты и многослойные документы.", "Большая диагональ особенно удобна с Apple Pencil Pro и Magic Keyboard, когда iPad становится рабочей станцией для пары, офиса или студии.", "Версии Wi-Fi и LTE помогают выбрать сценарий под себя: домашняя работа, учеба в кампусе или постоянная мобильность без привязки к раздаче интернета."]'::jsonb,
        'Assets/desktop/photo/ipadProM5/ipad-pro-13-m5-2025-wifi-space-black.png',
        FALSE,
        TRUE,
        TRUE,
        220
    ),
    (
        (SELECT id FROM categories WHERE slug = 'macbook'),
        'MacBook Neo',
        'macbook-neo-13-a18-pro',
        'Легкий MacBook Neo 13 на A18 Pro в ярких цветах.',
        '["MacBook Neo — самый дружелюбный вход в Mac: компактный 13-дюймовый формат, легкий корпус и понятная производительность для учебы, браузера, документов и медиа.", "A18 Pro быстро справляется с повседневными приложениями, AI-задачами и легким творчеством, сохраняя хорошую энергоэффективность на каждый день.", "Яркие цвета Blush, Indigo, Silver и Citrus делают ноутбук более личным и живым, особенно если не хочется очередной строгий серый корпус.", "Это хороший выбор для студентов, домашней работы и первого Mac, когда важны цена, автономность, macOS и аккуратный дизайн без профессиональной переплаты."]'::jsonb,
        'Assets/desktop/photo/macbookNeo/macbook-neo-a18-pro-2026-blush.png',
        TRUE,
        TRUE,
        FALSE,
        300
    ),
    (
        (SELECT id FROM categories WHERE slug = 'macbook'),
        'MacBook Air 13',
        'macbook-air-13-m5',
        'Тонкий 13-дюймовый MacBook Air на M5.',
        '["MacBook Air 13 легко брать с собой каждый день: он тонкий, помещается в рюкзак и не ощущается как тяжелая рабочая станция.", "M5 дает быстрый отклик в macOS, браузере, офисных приложениях, учебных проектах, легком монтаже и AI-инструментах без лишнего шума.", "До 18 часов автономности помогают спокойно пережить пары, рабочий день или поездку без постоянного поиска розетки.", "Несколько конфигураций памяти и накопителя позволяют выбрать спокойную базовую версию или собрать Air с запасом под проекты, фото и учебные файлы."]'::jsonb,
        'Assets/desktop/photo/macbookAir/macbook-air-13-m4-silver.png',
        TRUE,
        TRUE,
        FALSE,
        310
    ),
    (
        (SELECT id FROM categories WHERE slug = 'macbook'),
        'MacBook Air 15',
        'macbook-air-15-m5',
        'Большой MacBook Air на M5 с 15-дюймовым экраном.',
        '["MacBook Air 15 сохраняет легкость Air, но дает больше пространства на экране для таблиц, макетов, видео, браузера и нескольких окон рядом.", "M5 подходит для учебы, работы, презентаций, созвонов и творческих задач, а macOS остается быстрой даже при активной многозадачности.", "До 18 часов автономности делают 15-дюймовый Air удобным ноутбуком для дома, университета, офиса и поездок без тяжелого зарядного режима.", "Это вариант для тех, кому нужен большой экран, но не нужен вес и мощность MacBook Pro: комфортный баланс размера, тишины и мобильности."]'::jsonb,
        'Assets/desktop/photo/macbookAir/macbook-air-13-m4-skyblue.png',
        FALSE,
        TRUE,
        FALSE,
        320
    ),
    (
        (SELECT id FROM categories WHERE slug = 'macbook'),
        'MacBook Pro',
        'macbook-pro-14-m5-pro',
        'Профессиональный 14-дюймовый MacBook Pro на M5 Pro.',
        '["M5 Pro создан для тяжелых задач: монтаж, код, 3D, большие проекты, AI-инструменты и работа с несколькими профессиональными приложениями одновременно.", "Liquid Retina XDR дисплей с высокой HDR-яркостью и глубоким контрастом хорошо подходит для видео, фото, дизайна и точной работы с цветом.", "До 24 часов автономности и богатый набор портов делают MacBook Pro удобным не только на столе, но и в поездках, на съемках и в университете.", "Конфигурации с большим накопителем и памятью дают запас на годы, а корпус в Silver или Space Black выглядит строго, дорого и по-настоящему рабоче."]'::jsonb,
        'Assets/desktop/photo/macbookProM5/apple-macbook-pro-14-m5-late-2025-space-black.png',
        FALSE,
        TRUE,
        TRUE,
        330
    )
ON CONFLICT (slug) DO UPDATE SET
    category_id = EXCLUDED.category_id,
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    advantages = EXCLUDED.advantages,
    main_image = EXCLUDED.main_image,
    is_popular = EXCLUDED.is_popular,
    is_new = EXCLUDED.is_new,
    is_hit = EXCLUDED.is_hit,
    sort_order = EXCLUDED.sort_order,
    is_active = TRUE;

INSERT INTO product_images (product_id, image_path, alt, sort_order)
VALUES
    ((SELECT id FROM products WHERE slug = 'airpods-4'), 'Assets/desktop/photo/airpods4/airpods-4.png', 'AirPods 4', 10),
    ((SELECT id FROM products WHERE slug = 'airpods-pro-3'), 'Assets/desktop/photo/airpodsPro3/airpods-pro-3.png', 'AirPods Pro 3', 10),
    ((SELECT id FROM products WHERE slug = 'airpods-max-2'), 'Assets/desktop/photo/airpodsMax2/airpods-max-blue.png', 'AirPods Max 2', 10),
    ((SELECT id FROM products WHERE slug = 'airpods-max-2'), 'Assets/desktop/photo/airpodsMax2/airpods-max-midnight.png', 'AirPods Max 2 Midnight', 14),
    ((SELECT id FROM products WHERE slug = 'airpods-max-2'), 'Assets/desktop/photo/airpodsMax2/airpods-max-orange.png', 'AirPods Max 2 Orange', 15),
    ((SELECT id FROM products WHERE slug = 'iphone-17e'), 'Assets/desktop/photo/iphone17E/iphone-17e-black.png', 'iPhone 17e', 10),
    ((SELECT id FROM products WHERE slug = 'iphone-17e'), 'Assets/desktop/photo/iphone17E/iphone-17e-white.png', 'iPhone 17e White', 108),
    ((SELECT id FROM products WHERE slug = 'iphone-17e'), 'Assets/desktop/photo/iphone17E/iphone-17e-soft-pink.png', 'iPhone 17e Pink', 109),
    ((SELECT id FROM products WHERE slug = 'iphone-17'), 'Assets/desktop/photo/iphone17/iPhone_17_Sage/iphone-17-sage.png', 'iPhone 17', 10),
    ((SELECT id FROM products WHERE slug = 'iphone-17'), 'Assets/desktop/photo/iphone17/iPhone_17_Black/iphone-17-black.png', 'iPhone 17 Black', 121),
    ((SELECT id FROM products WHERE slug = 'iphone-17'), 'Assets/desktop/photo/iphone17/iPhone_17_Blue/iphone-17-mist-blue.png', 'iPhone 17 Blue', 122),
    ((SELECT id FROM products WHERE slug = 'iphone-17'), 'Assets/desktop/photo/iphone17/iPhone_17_White/iphone-17-white.png', 'iPhone 17 White', 123),
    ((SELECT id FROM products WHERE slug = 'iphone-17'), 'Assets/desktop/photo/iphone17/iPhone_17_Lavender/iphone-17-lavender.png', 'iPhone 17 Lavender', 125),
    ((SELECT id FROM products WHERE slug = 'iphone-air'), 'Assets/desktop/photo/iphoneAir/iphone-air-sky-blue.png', 'iPhone Air', 10),
    ((SELECT id FROM products WHERE slug = 'iphone-air'), 'Assets/desktop/photo/iphoneAir/iphone-air-light-gold.png', 'iPhone Air Light Gold', 138),
    ((SELECT id FROM products WHERE slug = 'iphone-air'), 'Assets/desktop/photo/iphoneAir/iphone-air-cloud-white.png', 'iPhone Air Cloud White', 139),
    ((SELECT id FROM products WHERE slug = 'iphone-air'), 'Assets/desktop/photo/iphoneAir/iphone-air-space-black.png', 'iPhone Air Space Black', 140),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro'), 'Assets/desktop/photo/iphone17PPM/iPhone_17_PPM_Silver/iphone-17-pro-max-silver.png', 'iPhone 17 Pro', 10),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro-max'), 'Assets/desktop/photo/iphone17PPM/iPhone_17_PPM_Orange/iphone-17-pro-max-cosmic-orange.png', 'iPhone 17 Pro Max', 10),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro'), 'Assets/desktop/photo/iphone17PPM/iPhone_17_PPM_Orange/iphone-17-pro-max-cosmic-orange.png', 'iPhone 17 Pro Cosmic Orange', 154),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro'), 'Assets/desktop/photo/iphone17PPM/iPhone_17_PPM_Blue/iphone-17-pro-max-deep-blue.png', 'iPhone 17 Pro Deep Blue', 155),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro-max'), 'Assets/desktop/photo/iphone17PPM/iPhone_17_PPM_Silver/iphone-17-pro-max-silver.png', 'iPhone 17 Pro Max Silver', 166),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro-max'), 'Assets/desktop/photo/iphone17PPM/iPhone_17_PPM_Blue/iphone-17-pro-max-deep-blue.png', 'iPhone 17 Pro Max Deep Blue', 168),
    ((SELECT id FROM products WHERE slug = 'ipad-11-a16-2025'), 'Assets/desktop/photo/ipad11/ipad-a16-2025-wifi-blue.png', 'iPad 11 A16 2025', 10),
    ((SELECT id FROM products WHERE slug = 'ipad-11-a16-2025'), 'Assets/desktop/photo/ipad11/ipad-a16-2025-wifi-silver.png', 'iPad 11 A16 2025 Silver', 231),
    ((SELECT id FROM products WHERE slug = 'ipad-11-a16-2025'), 'Assets/desktop/photo/ipad11/ipad-a16-2025-wifi-pink.png', 'iPad 11 A16 2025 Pink', 232),
    ((SELECT id FROM products WHERE slug = 'ipad-11-a16-2025'), 'Assets/desktop/photo/ipad11/ipad-a16-2025-wifi-yellow.png', 'iPad 11 A16 2025 Yellow', 233),
    ((SELECT id FROM products WHERE slug = 'ipad-pro-11-m5-2025'), 'Assets/desktop/photo/ipadProM5/ipad-pro-11-m5-2025-wifi-space-black.png', 'iPad Pro 11 M5 2025', 10),
    ((SELECT id FROM products WHERE slug = 'ipad-pro-11-m5-2025'), 'Assets/desktop/photo/ipadProM5/ipad-pro-11-m5-2025-wifi-silver.png', 'iPad Pro 11 M5 2025 Silver', 246),
    ((SELECT id FROM products WHERE slug = 'ipad-pro-13-m5-2025'), 'Assets/desktop/photo/ipadProM5/ipad-pro-13-m5-2025-wifi-space-black.png', 'iPad Pro 13 M5 2025', 10),
    ((SELECT id FROM products WHERE slug = 'ipad-pro-13-m5-2025'), 'Assets/desktop/photo/ipadProM5/ipad-pro-13-m5-2025-wifi-silver.png', 'iPad Pro 13 M5 2025 Silver', 259),
    ((SELECT id FROM products WHERE slug = 'macbook-neo-13-a18-pro'), 'Assets/desktop/photo/macbookNeo/macbook-neo-a18-pro-2026-blush.png', 'MacBook Neo', 10),
    ((SELECT id FROM products WHERE slug = 'macbook-neo-13-a18-pro'), 'Assets/desktop/photo/macbookNeo/macbook-neo-a18-pro-2026-indigo.png', 'MacBook Neo Indigo', 342),
    ((SELECT id FROM products WHERE slug = 'macbook-neo-13-a18-pro'), 'Assets/desktop/photo/macbookNeo/macbook-neo-a18-pro-2026-silver.png', 'MacBook Neo Silver', 343),
    ((SELECT id FROM products WHERE slug = 'macbook-neo-13-a18-pro'), 'Assets/desktop/photo/macbookNeo/macbook-neo-a18-pro-2026-citrus.png', 'MacBook Neo Citrus', 344),
    ((SELECT id FROM products WHERE slug = 'macbook-air-13-m5'), 'Assets/desktop/photo/macbookAir/macbook-air-13-m4-silver.png', 'MacBook Air 13', 10),
    ((SELECT id FROM products WHERE slug = 'macbook-air-15-m5'), 'Assets/desktop/photo/macbookAir/macbook-air-13-m4-skyblue.png', 'MacBook Air 15', 10),
    ((SELECT id FROM products WHERE slug = 'macbook-air-13-m5'), 'Assets/desktop/photo/macbookAir/macbook-air-13-m4-midnight.png', 'MacBook Air 13 Midnight', 357),
    ((SELECT id FROM products WHERE slug = 'macbook-air-13-m5'), 'Assets/desktop/photo/macbookAir/macbook-air-13-m4-starlight.png', 'MacBook Air 13 Starlight', 359),
    ((SELECT id FROM products WHERE slug = 'macbook-air-13-m5'), 'Assets/desktop/photo/macbookAir/macbook-air-13-m4-skyblue.png', 'MacBook Air 13 Sky Blue', 360),
    ((SELECT id FROM products WHERE slug = 'macbook-air-15-m5'), 'Assets/desktop/photo/macbookAir/macbook-air-13-m4-midnight.png', 'MacBook Air 15 Midnight', 371),
    ((SELECT id FROM products WHERE slug = 'macbook-air-15-m5'), 'Assets/desktop/photo/macbookAir/macbook-air-13-m4-silver.png', 'MacBook Air 15 Silver', 372),
    ((SELECT id FROM products WHERE slug = 'macbook-air-15-m5'), 'Assets/desktop/photo/macbookAir/macbook-air-13-m4-starlight.png', 'MacBook Air 15 Starlight', 373),
    ((SELECT id FROM products WHERE slug = 'macbook-pro-14-m5-pro'), 'Assets/desktop/photo/macbookProM5/apple-macbook-pro-14-m5-late-2025-space-black.png', 'MacBook Pro', 10),
    ((SELECT id FROM products WHERE slug = 'macbook-pro-14-m5-pro'), 'Assets/desktop/photo/macbookProM5/apple-macbook-pro-14-m5-late-2025-silver.png', 'MacBook Pro Silver', 387)
ON CONFLICT (product_id, image_path) DO UPDATE SET
    alt = EXCLUDED.alt,
    sort_order = EXCLUDED.sort_order;

INSERT INTO product_variants (product_id, sku, price, stock, parameters)
VALUES
    ((SELECT id FROM products WHERE slug = 'airpods-4'), 'AIRPODS-4-STANDARD', 8700, 8, '{"noiseCancellation": "Без шумоподавления"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'airpods-4'), 'AIRPODS-4-ANC', 13500, 6, '{"noiseCancellation": "С шумоподавлением"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'airpods-pro-3'), 'AIRPODS-PRO-3', 15900, 7, '{"noiseCancellation": "Активное шумоподавление"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'airpods-max-2'), 'AIRPODS-MAX-2-BLUE', 44500, 4, '{"color": "Blue"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'airpods-max-2'), 'AIRPODS-MAX-2-MIDNIGHT', 44500, 4, '{"color": "Midnight"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'airpods-max-2'), 'AIRPODS-MAX-2-ORANGE', 44500, 4, '{"color": "Orange"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'macbook-neo-13-a18-pro'), 'MACBOOK-NEO-13-A18-PRO-BLUSH', 49000, 3, '{"color": "Blush", "memory": "8GB", "storage": "256GB", "chip": "A18 Pro"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'macbook-neo-13-a18-pro'), 'MACBOOK-NEO-13-A18-PRO-INDIGO', 49000, 3, '{"color": "Indigo", "memory": "8GB", "storage": "256GB", "chip": "A18 Pro"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'macbook-neo-13-a18-pro'), 'MACBOOK-NEO-13-A18-PRO-SILVER', 49000, 3, '{"color": "Silver", "memory": "8GB", "storage": "256GB", "chip": "A18 Pro"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'macbook-neo-13-a18-pro'), 'MACBOOK-NEO-13-A18-PRO-CITRUS', 49000, 3, '{"color": "Citrus", "memory": "8GB", "storage": "256GB", "chip": "A18 Pro"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-11-a16-2025'), 'IPAD-11-A16-2025-128GB-SILVER-WI-FI', 30800, 3, '{"color": "Silver", "memory": "128GB", "connection": "Wi-Fi"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-11-a16-2025'), 'IPAD-11-A16-2025-128GB-PINK-WI-FI', 30800, 3, '{"color": "Pink", "memory": "128GB", "connection": "Wi-Fi"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-11-a16-2025'), 'IPAD-11-A16-2025-128GB-BLUE-WI-FI', 30500, 3, '{"color": "Blue", "memory": "128GB", "connection": "Wi-Fi"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-11-a16-2025'), 'IPAD-11-A16-2025-128GB-YELLOW-WI-FI', 30500, 3, '{"color": "Yellow", "memory": "128GB", "connection": "Wi-Fi"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-11-a16-2025'), 'IPAD-11-A16-2025-128GB-BLUE-LTE', 42000, 3, '{"color": "Blue", "memory": "128GB", "connection": "LTE"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-11-a16-2025'), 'IPAD-11-A16-2025-128GB-SILVER-LTE', 44000, 3, '{"color": "Silver", "memory": "128GB", "connection": "LTE"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-11-a16-2025'), 'IPAD-11-A16-2025-128GB-YELLOW-LTE', 42000, 3, '{"color": "Yellow", "memory": "128GB", "connection": "LTE"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-11-a16-2025'), 'IPAD-11-A16-2025-128GB-PINK-LTE', 43500, 3, '{"color": "Pink", "memory": "128GB", "connection": "LTE"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-11-a16-2025'), 'IPAD-11-A16-2025-256GB-SILVER-WI-FI', 39500, 3, '{"color": "Silver", "memory": "256GB", "connection": "Wi-Fi"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-11-a16-2025'), 'IPAD-11-A16-2025-256GB-PINK-WI-FI', 39500, 3, '{"color": "Pink", "memory": "256GB", "connection": "Wi-Fi"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-11-a16-2025'), 'IPAD-11-A16-2025-256GB-BLUE-WI-FI', 39500, 3, '{"color": "Blue", "memory": "256GB", "connection": "Wi-Fi"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-11-a16-2025'), 'IPAD-11-A16-2025-256GB-YELLOW-WI-FI', 39500, 3, '{"color": "Yellow", "memory": "256GB", "connection": "Wi-Fi"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-11-a16-2025'), 'IPAD-11-A16-2025-256GB-SILVER-LTE', 57000, 3, '{"color": "Silver", "memory": "256GB", "connection": "LTE"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-11-a16-2025'), 'IPAD-11-A16-2025-256GB-BLUE-LTE', 57800, 3, '{"color": "Blue", "memory": "256GB", "connection": "LTE"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-11-a16-2025'), 'IPAD-11-A16-2025-256GB-PINK-LTE', 56700, 3, '{"color": "Pink", "memory": "256GB", "connection": "LTE"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-11-a16-2025'), 'IPAD-11-A16-2025-256GB-YELLOW-LTE', 59000, 3, '{"color": "Yellow", "memory": "256GB", "connection": "LTE"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-11-a16-2025'), 'IPAD-11-A16-2025-512GB-BLUE-WI-FI', 59000, 3, '{"color": "Blue", "memory": "512GB", "connection": "Wi-Fi"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-11-a16-2025'), 'IPAD-11-A16-2025-512GB-SILVER-WI-FI', 59600, 3, '{"color": "Silver", "memory": "512GB", "connection": "Wi-Fi"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-pro-11-m5-2025'), 'ipad-pro-11-m5-2025-256GB-Space Black-Wi-Fi', 79000, 3, '{"color": "Space Black", "memory": "256GB", "connection": "Wi-Fi"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-pro-11-m5-2025'), 'ipad-pro-11-m5-2025-256GB-Silver-Wi-Fi', 79000, 3, '{"color": "Silver", "memory": "256GB", "connection": "Wi-Fi"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-pro-11-m5-2025'), 'ipad-pro-11-m5-2025-256GB-Space Black-LTE', 90000, 3, '{"color": "Space Black", "memory": "256GB", "connection": "LTE"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-pro-11-m5-2025'), 'ipad-pro-11-m5-2025-256GB-Silver-LTE', 90000, 3, '{"color": "Silver", "memory": "256GB", "connection": "LTE"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-pro-11-m5-2025'), 'ipad-pro-11-m5-2025-512GB-Space Black-Wi-Fi', 95000, 3, '{"color": "Space Black", "memory": "512GB", "connection": "Wi-Fi"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-pro-11-m5-2025'), 'ipad-pro-11-m5-2025-512GB-Silver-Wi-Fi', 95000, 3, '{"color": "Silver", "memory": "512GB", "connection": "Wi-Fi"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-pro-11-m5-2025'), 'ipad-pro-11-m5-2025-512GB-Space Black-LTE', 115000, 3, '{"color": "Space Black", "memory": "512GB", "connection": "LTE"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-pro-11-m5-2025'), 'ipad-pro-11-m5-2025-512GB-Silver-LTE', 115000, 3, '{"color": "Silver", "memory": "512GB", "connection": "LTE"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-pro-13-m5-2025'), 'ipad-pro-13-m5-2025-256GB-Space Black-Wi-Fi', 92000, 3, '{"color": "Space Black", "memory": "256GB", "connection": "Wi-Fi"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-pro-13-m5-2025'), 'ipad-pro-13-m5-2025-256GB-Silver-Wi-Fi', 94000, 3, '{"color": "Silver", "memory": "256GB", "connection": "Wi-Fi"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-pro-13-m5-2025'), 'ipad-pro-13-m5-2025-256GB-Space Black-LTE', 93500, 3, '{"color": "Space Black", "memory": "256GB", "connection": "LTE"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-pro-13-m5-2025'), 'ipad-pro-13-m5-2025-256GB-Silver-LTE', 98000, 3, '{"color": "Silver", "memory": "256GB", "connection": "LTE"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-pro-13-m5-2025'), 'ipad-pro-13-m5-2025-512GB-Space Black-Wi-Fi', 111500, 3, '{"color": "Space Black", "memory": "512GB", "connection": "Wi-Fi"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-pro-13-m5-2025'), 'ipad-pro-13-m5-2025-512GB-Silver-Wi-Fi', 112000, 3, '{"color": "Silver", "memory": "512GB", "connection": "Wi-Fi"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-pro-13-m5-2025'), 'ipad-pro-13-m5-2025-512GB-Space Black-LTE', 114000, 3, '{"color": "Space Black", "memory": "512GB", "connection": "LTE"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-pro-13-m5-2025'), 'ipad-pro-13-m5-2025-512GB-Silver-LTE', 117000, 3, '{"color": "Silver", "memory": "512GB", "connection": "LTE"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-pro-13-m5-2025'), 'ipad-pro-13-m5-2025-1TB-Space Black-Wi-Fi', 133000, 3, '{"color": "Space Black", "memory": "1TB", "connection": "Wi-Fi"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-pro-13-m5-2025'), 'ipad-pro-13-m5-2025-1TB-Space Black-LTE', 132000, 3, '{"color": "Space Black", "memory": "1TB", "connection": "LTE"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-pro-13-m5-2025'), 'ipad-pro-13-m5-2025-1TB-Silver-LTE', 136000, 3, '{"color": "Silver", "memory": "1TB", "connection": "LTE"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-pro-13-m5-2025'), 'ipad-pro-13-m5-2025-2TB-Space Black-LTE', 142000, 3, '{"color": "Space Black", "memory": "2TB", "connection": "LTE"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'ipad-pro-13-m5-2025'), 'ipad-pro-13-m5-2025-2TB-Silver-LTE', 145000, 3, '{"color": "Silver", "memory": "2TB", "connection": "LTE"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17e'), 'IPHONE-17E-256GB-BLACK-SIM-PLUS-ESIM', 56500, 3, '{"color": "Black", "memory": "256GB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17e'), 'IPHONE-17E-256GB-BLACK-ESIM', 51500, 3, '{"color": "Black", "memory": "256GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17e'), 'IPHONE-17E-256GB-WHITE-SIM-PLUS-ESIM', 46000, 3, '{"color": "White", "memory": "256GB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17e'), 'IPHONE-17E-256GB-WHITE-ESIM', 49000, 3, '{"color": "White", "memory": "256GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17e'), 'IPHONE-17E-256GB-PINK-SIM-PLUS-ESIM', 46000, 3, '{"color": "Pink", "memory": "256GB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17e'), 'IPHONE-17E-256GB-PINK-ESIM', 47000, 3, '{"color": "Pink", "memory": "256GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17e'), 'IPHONE-17E-512GB-PINK-ESIM', 57500, 3, '{"color": "Pink", "memory": "512GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17'), 'IPHONE-17-256GB-BLACK-SIM-PLUS-ESIM', 65700, 3, '{"color": "Black", "memory": "256GB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17'), 'IPHONE-17-256GB-BLACK-ESIM', 60500, 3, '{"color": "Black", "memory": "256GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17'), 'IPHONE-17-256GB-BLUE-SIM-PLUS-ESIM', 65500, 3, '{"color": "Blue", "memory": "256GB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17'), 'IPHONE-17-256GB-BLUE-ESIM', 60500, 3, '{"color": "Blue", "memory": "256GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17'), 'IPHONE-17-256GB-WHITE-SIM-PLUS-ESIM', 65800, 3, '{"color": "White", "memory": "256GB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17'), 'IPHONE-17-256GB-WHITE-ESIM', 63000, 3, '{"color": "White", "memory": "256GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17'), 'IPHONE-17-256GB-SAGE-SIM-PLUS-ESIM', 65800, 3, '{"color": "Sage", "memory": "256GB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17'), 'IPHONE-17-256GB-SAGE-ESIM', 63000, 3, '{"color": "Sage", "memory": "256GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17'), 'IPHONE-17-256GB-LAVENDER-SIM-PLUS-ESIM', 65800, 3, '{"color": "Lavender", "memory": "256GB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17'), 'IPHONE-17-256GB-LAVENDER-ESIM', 63000, 3, '{"color": "Lavender", "memory": "256GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17'), 'IPHONE-17-512GB-WHITE-SIM-PLUS-ESIM', 95000, 3, '{"color": "White", "memory": "512GB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17'), 'IPHONE-17-512GB-WHITE-ESIM', 84500, 3, '{"color": "White", "memory": "512GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17'), 'IPHONE-17-512GB-SAGE-SIM-PLUS-ESIM', 94500, 3, '{"color": "Sage", "memory": "512GB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17'), 'IPHONE-17-512GB-SAGE-ESIM', 82000, 3, '{"color": "Sage", "memory": "512GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17'), 'IPHONE-17-512GB-BLUE-SIM-PLUS-ESIM', 93500, 3, '{"color": "Blue", "memory": "512GB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17'), 'IPHONE-17-512GB-BLUE-ESIM', 80000, 3, '{"color": "Blue", "memory": "512GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17'), 'IPHONE-17-512GB-LAVENDER-SIM-PLUS-ESIM', 97000, 3, '{"color": "Lavender", "memory": "512GB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17'), 'IPHONE-17-512GB-LAVENDER-ESIM', 81500, 3, '{"color": "Lavender", "memory": "512GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17'), 'IPHONE-17-512GB-BLACK-SIM-PLUS-ESIM', 93000, 3, '{"color": "Black", "memory": "512GB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17'), 'IPHONE-17-512GB-BLACK-ESIM', 79000, 3, '{"color": "Black", "memory": "512GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-air'), 'IPHONE-AIR-256GB-SKY-BLUE-ESIM', 66700, 3, '{"color": "Sky Blue", "memory": "256GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-air'), 'IPHONE-AIR-256GB-LIGHT-GOLD-ESIM', 68000, 3, '{"color": "Light Gold", "memory": "256GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-air'), 'IPHONE-AIR-256GB-CLOUD-WHITE-ESIM', 68700, 3, '{"color": "Cloud White", "memory": "256GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-air'), 'IPHONE-AIR-256GB-SPACE-BLACK-ESIM', 68000, 3, '{"color": "Space Black", "memory": "256GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-air'), 'IPHONE-AIR-512GB-SKY-BLUE-ESIM', 83000, 3, '{"color": "Sky Blue", "memory": "512GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-air'), 'IPHONE-AIR-512GB-LIGHT-GOLD-ESIM', 85500, 3, '{"color": "Light Gold", "memory": "512GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-air'), 'IPHONE-AIR-512GB-CLOUD-WHITE-ESIM', 87500, 3, '{"color": "Cloud White", "memory": "512GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-air'), 'IPHONE-AIR-512GB-SPACE-BLACK-ESIM', 83000, 3, '{"color": "Space Black", "memory": "512GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-air'), 'IPHONE-AIR-1TB-SKY-BLUE-ESIM', 89500, 3, '{"color": "Sky Blue", "memory": "1TB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-air'), 'IPHONE-AIR-1TB-LIGHT-GOLD-ESIM', 91500, 3, '{"color": "Light Gold", "memory": "1TB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-air'), 'IPHONE-AIR-1TB-CLOUD-WHITE-ESIM', 93000, 3, '{"color": "Cloud White", "memory": "1TB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-air'), 'IPHONE-AIR-1TB-SPACE-BLACK-ESIM', 94000, 3, '{"color": "Space Black", "memory": "1TB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro'), 'IPHONE-17-PRO-256GB-SILVER-SIM-ESIM', 94400, 3, '{"color": "Silver", "memory": "256GB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro'), 'IPHONE-17-PRO-256GB-SILVER-ESIM', 88000, 3, '{"color": "Silver", "memory": "256GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro'), 'IPHONE-17-PRO-256GB-COSMIC-ORANGE-SIM-ESIM', 92400, 3, '{"color": "Cosmic Orange", "memory": "256GB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro'), 'IPHONE-17-PRO-256GB-COSMIC-ORANGE-ESIM', 84000, 3, '{"color": "Cosmic Orange", "memory": "256GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro'), 'IPHONE-17-PRO-256GB-DEEP-BLUE-SIM-ESIM', 94400, 3, '{"color": "Deep Blue", "memory": "256GB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro'), 'IPHONE-17-PRO-256GB-DEEP-BLUE-ESIM', 85500, 3, '{"color": "Deep Blue", "memory": "256GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro'), 'IPHONE-17-PRO-512GB-SILVER-SIM-ESIM', 111000, 3, '{"color": "Silver", "memory": "512GB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro'), 'IPHONE-17-PRO-512GB-SILVER-ESIM', 104000, 3, '{"color": "Silver", "memory": "512GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro'), 'IPHONE-17-PRO-512GB-COSMIC-ORANGE-SIM-ESIM', 107500, 3, '{"color": "Cosmic Orange", "memory": "512GB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro'), 'IPHONE-17-PRO-512GB-COSMIC-ORANGE-ESIM', 102000, 3, '{"color": "Cosmic Orange", "memory": "512GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro'), 'IPHONE-17-PRO-512GB-DEEP-BLUE-SIM-ESIM', 110000, 3, '{"color": "Deep Blue", "memory": "512GB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro'), 'IPHONE-17-PRO-512GB-DEEP-BLUE-ESIM', 103500, 3, '{"color": "Deep Blue", "memory": "512GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro'), 'IPHONE-17-PRO-1TB-SILVER-SIM-ESIM', 128000, 3, '{"color": "Silver", "memory": "1TB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro'), 'IPHONE-17-PRO-1TB-SILVER-ESIM', 125000, 3, '{"color": "Silver", "memory": "1TB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro'), 'IPHONE-17-PRO-1TB-COSMIC-ORANGE-SIM-ESIM', 127600, 3, '{"color": "Cosmic Orange", "memory": "1TB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro'), 'IPHONE-17-PRO-1TB-COSMIC-ORANGE-ESIM', 120000, 3, '{"color": "Cosmic Orange", "memory": "1TB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro'), 'IPHONE-17-PRO-1TB-DEEP-BLUE-SIM-ESIM', 127000, 3, '{"color": "Deep Blue", "memory": "1TB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro'), 'IPHONE-17-PRO-1TB-DEEP-BLUE-ESIM', 121000, 3, '{"color": "Deep Blue", "memory": "1TB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro-max'), 'IPHONE-17-PRO-MAX-256GB-SILVER-SIM-ESIM', 106500, 3, '{"color": "Silver", "memory": "256GB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro-max'), 'IPHONE-17-PRO-MAX-256GB-SILVER-ESIM', 95000, 3, '{"color": "Silver", "memory": "256GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro-max'), 'IPHONE-17-PRO-MAX-256GB-COSMIC-ORANGE-SIM-ESIM', 102700, 3, '{"color": "Cosmic Orange", "memory": "256GB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro-max'), 'IPHONE-17-PRO-MAX-256GB-COSMIC-ORANGE-ESIM', 89000, 3, '{"color": "Cosmic Orange", "memory": "256GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro-max'), 'IPHONE-17-PRO-MAX-256GB-DEEP-BLUE-SIM-ESIM', 105500, 3, '{"color": "Deep Blue", "memory": "256GB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro-max'), 'IPHONE-17-PRO-MAX-256GB-DEEP-BLUE-ESIM', 89500, 3, '{"color": "Deep Blue", "memory": "256GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro-max'), 'IPHONE-17-PRO-MAX-512GB-SILVER-SIM-ESIM', 124000, 3, '{"color": "Silver", "memory": "512GB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro-max'), 'IPHONE-17-PRO-MAX-512GB-SILVER-ESIM', 111000, 3, '{"color": "Silver", "memory": "512GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro-max'), 'IPHONE-17-PRO-MAX-512GB-COSMIC-ORANGE-SIM-ESIM', 119000, 3, '{"color": "Cosmic Orange", "memory": "512GB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro-max'), 'IPHONE-17-PRO-MAX-512GB-COSMIC-ORANGE-ESIM', 105500, 3, '{"color": "Cosmic Orange", "memory": "512GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro-max'), 'IPHONE-17-PRO-MAX-512GB-DEEP-BLUE-SIM-ESIM', 120000, 3, '{"color": "Deep Blue", "memory": "512GB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro-max'), 'IPHONE-17-PRO-MAX-512GB-DEEP-BLUE-ESIM', 110500, 3, '{"color": "Deep Blue", "memory": "512GB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro-max'), 'IPHONE-17-PRO-MAX-1TB-SILVER-SIM-ESIM', 139500, 3, '{"color": "Silver", "memory": "1TB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro-max'), 'IPHONE-17-PRO-MAX-1TB-SILVER-ESIM', 127000, 3, '{"color": "Silver", "memory": "1TB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro-max'), 'IPHONE-17-PRO-MAX-1TB-COSMIC-ORANGE-SIM-ESIM', 139500, 3, '{"color": "Cosmic Orange", "memory": "1TB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro-max'), 'IPHONE-17-PRO-MAX-1TB-COSMIC-ORANGE-ESIM', 127000, 3, '{"color": "Cosmic Orange", "memory": "1TB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro-max'), 'IPHONE-17-PRO-MAX-1TB-DEEP-BLUE-SIM-ESIM', 139500, 3, '{"color": "Deep Blue", "memory": "1TB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro-max'), 'IPHONE-17-PRO-MAX-1TB-DEEP-BLUE-ESIM', 127000, 3, '{"color": "Deep Blue", "memory": "1TB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro-max'), 'IPHONE-17-PRO-MAX-2TB-SILVER-SIM-ESIM', 168000, 3, '{"color": "Silver", "memory": "2TB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro-max'), 'IPHONE-17-PRO-MAX-2TB-SILVER-ESIM', 158000, 3, '{"color": "Silver", "memory": "2TB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro-max'), 'IPHONE-17-PRO-MAX-2TB-COSMIC-ORANGE-SIM-ESIM', 166000, 3, '{"color": "Cosmic Orange", "memory": "2TB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro-max'), 'IPHONE-17-PRO-MAX-2TB-COSMIC-ORANGE-ESIM', 134500, 3, '{"color": "Cosmic Orange", "memory": "2TB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro-max'), 'IPHONE-17-PRO-MAX-2TB-DEEP-BLUE-SIM-ESIM', 166000, 3, '{"color": "Deep Blue", "memory": "2TB", "sim": "SIM + eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'iphone-17-pro-max'), 'IPHONE-17-PRO-MAX-2TB-DEEP-BLUE-ESIM', 151000, 3, '{"color": "Deep Blue", "memory": "2TB", "sim": "eSIM"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'macbook-air-13-m5'), 'MACBOOK-AIR-13-M5-16-512-SILVER', 90000, 3, '{"color": "Silver", "memory": "16GB", "storage": "512GB", "chip": "M5"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'macbook-air-13-m5'), 'MACBOOK-AIR-13-M5-16-512-STARLIGHT', 89000, 3, '{"color": "Starlight", "memory": "16GB", "storage": "512GB", "chip": "M5"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'macbook-air-13-m5'), 'MACBOOK-AIR-13-M5-16-512-MIDNIGHT', 90000, 3, '{"color": "Midnight", "memory": "16GB", "storage": "512GB", "chip": "M5"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'macbook-air-13-m5'), 'MACBOOK-AIR-13-M5-16-512-SKY-BLUE', 90000, 3, '{"color": "Sky Blue", "memory": "16GB", "storage": "512GB", "chip": "M5"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'macbook-air-13-m5'), 'MACBOOK-AIR-13-M5-16-1TB-MIDNIGHT', 106000, 3, '{"color": "Midnight", "memory": "16GB", "storage": "1TB", "chip": "M5"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'macbook-air-13-m5'), 'MACBOOK-AIR-13-M5-16-1TB-SILVER', 106000, 3, '{"color": "Silver", "memory": "16GB", "storage": "1TB", "chip": "M5"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'macbook-air-13-m5'), 'MACBOOK-AIR-13-M5-16-1TB-STARLIGHT', 106000, 3, '{"color": "Starlight", "memory": "16GB", "storage": "1TB", "chip": "M5"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'macbook-air-13-m5'), 'MACBOOK-AIR-13-M5-16-1TB-SKY-BLUE', 106000, 3, '{"color": "Sky Blue", "memory": "16GB", "storage": "1TB", "chip": "M5"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'macbook-air-13-m5'), 'MACBOOK-AIR-13-M5-24-1TB-MIDNIGHT', 124000, 2, '{"color": "Midnight", "memory": "24GB", "storage": "1TB", "chip": "M5"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'macbook-air-13-m5'), 'MACBOOK-AIR-13-M5-24-1TB-SKY-BLUE', 124000, 2, '{"color": "Sky Blue", "memory": "24GB", "storage": "1TB", "chip": "M5"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'macbook-air-13-m5'), 'MACBOOK-AIR-13-M5-24-1TB-STARLIGHT', 124000, 2, '{"color": "Starlight", "memory": "24GB", "storage": "1TB", "chip": "M5"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'macbook-air-15-m5'), 'MACBOOK-AIR-15-M5-16-512-MIDNIGHT', 102000, 3, '{"color": "Midnight", "memory": "16GB", "storage": "512GB", "chip": "M5"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'macbook-air-15-m5'), 'MACBOOK-AIR-15-M5-16-512-SKY-BLUE', 102000, 3, '{"color": "Sky Blue", "memory": "16GB", "storage": "512GB", "chip": "M5"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'macbook-air-15-m5'), 'MACBOOK-AIR-15-M5-16-512-STARLIGHT', 102000, 3, '{"color": "Starlight", "memory": "16GB", "storage": "512GB", "chip": "M5"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'macbook-air-15-m5'), 'MACBOOK-AIR-15-M5-16-512-SILVER', 103000, 3, '{"color": "Silver", "memory": "16GB", "storage": "512GB", "chip": "M5"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'macbook-air-15-m5'), 'MACBOOK-AIR-15-M5-16-1TB-MIDNIGHT', 119000, 3, '{"color": "Midnight", "memory": "16GB", "storage": "1TB", "chip": "M5"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'macbook-air-15-m5'), 'MACBOOK-AIR-15-M5-16-1TB-STARLIGHT', 119000, 3, '{"color": "Starlight", "memory": "16GB", "storage": "1TB", "chip": "M5"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'macbook-air-15-m5'), 'MACBOOK-AIR-15-M5-16-1TB-SKY-BLUE', 119000, 3, '{"color": "Sky Blue", "memory": "16GB", "storage": "1TB", "chip": "M5"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'macbook-air-15-m5'), 'MACBOOK-AIR-15-M5-16-1TB-SILVER', 122000, 3, '{"color": "Silver", "memory": "16GB", "storage": "1TB", "chip": "M5"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'macbook-air-15-m5'), 'MACBOOK-AIR-15-M5-24-1TB-MIDNIGHT', 138000, 2, '{"color": "Midnight", "memory": "24GB", "storage": "1TB", "chip": "M5"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'macbook-air-15-m5'), 'MACBOOK-AIR-15-M5-24-1TB-SILVER', 142000, 2, '{"color": "Silver", "memory": "24GB", "storage": "1TB", "chip": "M5"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'macbook-air-15-m5'), 'MACBOOK-AIR-15-M5-24-1TB-SKY-BLUE', 138000, 2, '{"color": "Sky Blue", "memory": "24GB", "storage": "1TB", "chip": "M5"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'macbook-air-15-m5'), 'MACBOOK-AIR-15-M5-24-1TB-STARLIGHT', 138000, 2, '{"color": "Starlight", "memory": "24GB", "storage": "1TB", "chip": "M5"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'macbook-pro-14-m5-pro'), 'MACBOOK-PRO-14-M5-PRO-24-1TB-SILVER', 178000, 2, '{"color": "Silver", "memory": "24GB", "storage": "1TB", "chip": "M5 Pro"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'macbook-pro-14-m5-pro'), 'MACBOOK-PRO-14-M5-PRO-24-1TB-SPACE-BLACK', 179000, 2, '{"color": "Space Black", "memory": "24GB", "storage": "1TB", "chip": "M5 Pro"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'macbook-pro-14-m5-pro'), 'MACBOOK-PRO-14-M5-PRO-24-2TB-SPACE-BLACK', 202000, 2, '{"color": "Space Black", "memory": "24GB", "storage": "2TB", "chip": "M5 Pro"}'::jsonb),
    ((SELECT id FROM products WHERE slug = 'macbook-pro-14-m5-pro'), 'MACBOOK-PRO-14-M5-PRO-24-2TB-SILVER', 202000, 2, '{"color": "Silver", "memory": "24GB", "storage": "2TB", "chip": "M5 Pro"}'::jsonb)
ON CONFLICT (sku) DO UPDATE SET
    product_id = EXCLUDED.product_id,
    price = EXCLUDED.price,
    stock = EXCLUDED.stock,
    parameters = EXCLUDED.parameters,
    is_active = TRUE;

DELETE FROM product_variants
WHERE is_active = FALSE;

DELETE FROM products
WHERE is_active = FALSE;

COMMIT;
